//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class tasks
    {
        public int id { get; set; }
        public string description { get; set; }
        public Nullable<int> idImportance { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> idUser { get; set; }
    
        public virtual importance importance { get; set; }
        public virtual users users { get; set; }
    }
}
